name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          export PYTHONPATH=$PWD  # Sets PYTHONPATH to the workflow's root directory
          pytest tests/test_app.py -v

      - name: Build Docker image
        run: |
          docker build -t hivebox:0.0.1 .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name hivebox hivebox:0.0.2
          sleep 5

      - name: Test /version endpoint
        run: |
          curl -f http://localhost:5000/version | grep '"version": "v0.0.1"' || (echo "Version test failed" && exit 1)

      - name: Stop container
        if: always()
        run: |
          docker stop hivebox
